import { useCallback, useEffect, useState } from 'react';
import {
  Trophy,
  Clock,
  CheckCircle2,
  ArrowRight,
  AlertTriangle,
  Flame,
} from 'lucide-react';

const QUESTION_COUNT = 3;
const OPTION_CHARS = ['A', 'B', 'C', 'D'];

const getLessonContext = (lessonParagraphs = []) =>
  lessonParagraphs
    .filter(Boolean)
    .map((paragraph) => paragraph.trim())
    .filter(Boolean)
    .join('\n\n');

const summarizeParagraph = (paragraph, fallback) => {
  if (!paragraph) return fallback;
  const firstSentence = paragraph.split(/[.!?]/).find((part) => part.trim().length > 20);
  return (firstSentence || paragraph).trim();
};

// Offline fallback quiz generator that uses the same explanation shown in class.
const getMockQuiz = (topic, lessonParagraphs = []) => {
  const firstConcept = summarizeParagraph(
    lessonParagraphs[0],
    `The explanation introduced the foundational ideas of ${topic}.`
  );
  const practicalConcept = summarizeParagraph(
    lessonParagraphs[2],
    `The explanation connected ${topic} to real-world constraints and applications.`
  );
  const synthesisConcept = summarizeParagraph(
    lessonParagraphs[3],
    `The explanation closed by connecting theory, observation, and problem solving.`
  );

  return [
    {
      id: 1,
      question: `Which statement best matches the first part of the explanation for "${topic}"?`,
      options: [
        firstConcept,
        'The topic was described as unrelated to variables or interactions.',
        'The topic was presented only as a historical fact to memorize.',
        'The lesson skipped the core idea and focused only on final scoring.',
      ],
      correct: 'A',
      explanation: firstConcept,
    },
    {
      id: 2,
      question: `What kind of practical thinking did the explanation connect to "${topic}"?`,
      options: [
        'Ignoring real-world conditions because theory is always exact',
        practicalConcept,
        'Avoiding models, examples, and observed evidence',
        'Replacing analysis with guessing when a system changes',
      ],
      correct: 'B',
      explanation: practicalConcept,
    },
    {
      id: 3,
      question: `Why should students understand "${topic}" after the explanation?`,
      options: [
        'It removes the need to test ideas or compare outcomes.',
        'It is useful only when every condition is perfectly ideal.',
        synthesisConcept,
        'It matters only for remembering definitions without application.',
      ],
      correct: 'C',
      explanation: synthesisConcept,
    },
  ];
};

const cleanJsonString = (rawText) => {
  let cleaned = rawText.trim();
  // Strip markdown code fences if generated by the model
  if (cleaned.startsWith('```')) {
    cleaned = cleaned.replace(/^```(json)?/i, '').replace(/```$/, '').trim();
  }

  const arrayStart = cleaned.indexOf('[');
  const arrayEnd = cleaned.lastIndexOf(']');
  if (arrayStart !== -1 && arrayEnd !== -1 && arrayEnd > arrayStart) {
    cleaned = cleaned.slice(arrayStart, arrayEnd + 1);
  }

  return cleaned;
};

const normalizeOptions = (rawOptions, fallbackOptions) => {
  let options = [];

  if (Array.isArray(rawOptions)) {
    options = rawOptions;
  } else if (rawOptions && typeof rawOptions === 'object') {
    options = OPTION_CHARS.map((char) => rawOptions[char] || rawOptions[char.toLowerCase()]);
  }

  const cleanedOptions = options
    .slice(0, 4)
    .map((option) =>
      String(option || '')
        .replace(/^[A-D][).:\-\s]+/i, '')
        .trim()
    )
    .filter(Boolean);

  return cleanedOptions.length === 4 ? cleanedOptions : fallbackOptions;
};

const normalizeCorrectAnswer = (rawCorrect, options, fallbackCorrect) => {
  if (typeof rawCorrect === 'number' && rawCorrect >= 0 && rawCorrect < 4) {
    return OPTION_CHARS[rawCorrect];
  }

  if (typeof rawCorrect !== 'string') {
    return fallbackCorrect;
  }

  const trimmed = rawCorrect.trim();
  const firstLetter = trimmed.charAt(0).toUpperCase();
  if (OPTION_CHARS.includes(firstLetter)) {
    return firstLetter;
  }

  const optionIndex = options.findIndex(
    (option) => option.toLowerCase() === trimmed.toLowerCase()
  );
  return optionIndex >= 0 ? OPTION_CHARS[optionIndex] : fallbackCorrect;
};

const normalizeQuiz = (parsed, topicName, lessonParagraphs) => {
  const fallbackQuiz = getMockQuiz(topicName, lessonParagraphs);
  const sourceQuestions = Array.isArray(parsed) ? parsed.slice(0, QUESTION_COUNT) : [];

  const generatedQuestions = sourceQuestions.map((q, idx) => {
    const fallback = fallbackQuiz[idx];
    const options = normalizeOptions(q.options, fallback.options);
    return {
      id: idx + 1,
      question: String(q.question || fallback.question).trim(),
      options,
      correct: normalizeCorrectAnswer(q.correct ?? q.answer, options, fallback.correct),
      explanation: q.explanation || fallback.explanation || 'Correct choice verified.',
    };
  });

  return [...generatedQuestions, ...fallbackQuiz.slice(generatedQuestions.length)].slice(
    0,
    QUESTION_COUNT
  );
};

export default function Quiz({
  onNext,
  onQuizResults,
  topicName,
  lessonParagraphs = [],
  apiKey,
}) {
  const [questions, setQuestions] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  // Quiz state
  const [selectedAnswers, setSelectedAnswers] = useState({ 0: null, 1: null, 2: null });
  const [timeLeft, setTimeLeft] = useState(180); // 3 minutes = 180 seconds
  const [submitted, setSubmitted] = useState(false);
  const [score, setScore] = useState(0);
  const [countdownTransition, setCountdownTransition] = useState(5); // 5 seconds result screen

  // 1. Fetch dynamic quiz questions or fallback
  useEffect(() => {
    let active = true;
    const fetchQuiz = async (canRetry = true) => {
      setLoading(true);
      setError(null);

      const lessonContext = getLessonContext(lessonParagraphs);
      const promptText = `Generate exactly 3 multiple choice questions based on the topic and teaching explanation below.

Topic: ${topicName}

Teaching explanation:
${lessonContext || 'Use the topic name because no transcript is available.'}

Each question must have 4 meaningful answer options and one correct answer. Return valid JSON only in this format: [{"question": "", "options": ["answer text", "answer text", "answer text", "answer text"], "correct": "A", "explanation": ""}].`;

      if (!apiKey) {
        setTimeout(() => {
          if (active) {
            setQuestions(getMockQuiz(topicName, lessonParagraphs));
            setLoading(false);
          }
        }, 1000);
        return;
      }

      try {
        const response = await fetch(
          `https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent?key=${apiKey}`,
          {
            method: 'POST',
            headers: {
              'Content-Type': 'application/json',
            },
            body: JSON.stringify({
              contents: [
                {
                  parts: [
                    {
                      text: promptText,
                    },
                  ],
                },
              ],
            }),
          }
        );

        if (!response.ok) {
          throw new Error(`Gemini API returned status ${response.status}`);
        }

        const data = await response.json();
        const text = data.candidates?.[0]?.content?.parts?.[0]?.text;
        
        if (!text) {
          throw new Error("No content candidates returned from Gemini API");
        }

        const cleaned = cleanJsonString(text);
        const parsed = JSON.parse(cleaned);

        if (!Array.isArray(parsed) || parsed.length === 0) {
          throw new Error("Quiz parsing failed: output is not a JSON array.");
        }

        if (active) {
          setQuestions(normalizeQuiz(parsed, topicName, lessonParagraphs));
          setLoading(false);
        }
      } catch (err) {
        console.error("Gemini quiz load failed:", err);
        if (canRetry && active) {
          console.log("Retrying Gemini quiz query once...");
          setTimeout(() => {
            if (active) {
              fetchQuiz(false);
            }
          }, 1000);
        } else {
          if (active) {
            setError(err.message || "Failed to load quiz from API");
            setQuestions(getMockQuiz(topicName, lessonParagraphs));
            setLoading(false);
          }
        }
      }
    };

    fetchQuiz(true);

    return () => {
      active = false;
    };
  }, [topicName, apiKey, lessonParagraphs]);

  // Submit and scoring calculation
  const handleSubmit = useCallback(() => {
    if (submitted) return;

    let finalScore = 0;
    const answersBreakdown = questions.map((q, idx) => {
      const selected = selectedAnswers[idx];
      const isCorrect = selected === q.correct;
      if (isCorrect) finalScore += 1;
      
      return {
        questionId: q.id,
        questionText: q.question,
        selected: selected || -1, // -1 means unanswered/timeout
        correct: q.correct,
        isCorrect,
      };
    });

    setScore(finalScore);
    setSubmitted(true);

    // Call state update in parent (triggers strike increments and result logs)
    onQuizResults({
      score: finalScore,
      total: questions.length,
      answers: answersBreakdown,
    });
  }, [onQuizResults, questions, selectedAnswers, submitted]);

  // 2. Countdown timer (3 minutes limit)
  useEffect(() => {
    if (loading || submitted) return;
    if (timeLeft <= 0) {
      const submitTimer = setTimeout(handleSubmit, 0);
      return () => clearTimeout(submitTimer);
    }
    const timer = setTimeout(() => setTimeLeft((t) => t - 1), 1000);
    return () => clearTimeout(timer);
  }, [timeLeft, submitted, loading, handleSubmit]);

  // 3. Post-submission 5-second redirect countdown timer
  useEffect(() => {
    if (!submitted) return;
    if (countdownTransition <= 0) {
      onNext();
      return;
    }
    const timer = setTimeout(() => setCountdownTransition((c) => c - 1), 1000);
    return () => clearTimeout(timer);
  }, [submitted, countdownTransition, onNext]);

  // Form option selection handler
  const handleSelect = (questionIdx, optionChar) => {
    if (submitted) return;
    setSelectedAnswers((prev) => ({
      ...prev,
      [questionIdx]: optionChar,
    }));
  };

  // Format MM:SS for 3 minute countdown timer
  const formatTime = (secs) => {
    const m = Math.floor(secs / 60);
    const s = secs % 60;
    return `${m.toString().padStart(2, '0')}:${s.toString().padStart(2, '0')}`;
  };

  if (loading) {
    return (
      <div className="flex-1 flex flex-col items-center justify-center px-4 py-12 relative">
        <div className="orb orb-purple w-72 h-72 top-10 right-10" />
        <div className="w-10 h-10 rounded-full border-4 border-slate-700 border-t-cyber-purple animate-spin mb-4" />
        <h2 className="text-xl font-bold text-white mb-2 tracking-tight">
          AI is loading...
        </h2>
        <p className="text-slate-400 text-xs font-mono">
          Formulating questions for: {topicName}
        </p>
      </div>
    );
  }

  // Display brief results overlay screen for 5 seconds
  if (submitted) {
    const hasStrike = score === 0;

    return (
      <div className="flex-1 flex items-center justify-center px-4 py-12 relative">
        <div className={`orb ${hasStrike ? 'orb-green' : 'orb-blue'} w-80 h-80 -top-20 -right-20`} />
        
        <div className="w-full max-w-md relative z-10 text-center animate-slide-up">
          <div className="glass p-8 mb-6 gradient-border">
            <h1 className="text-3xl font-extrabold text-white mb-2 font-display">
              Quiz Submitted!
            </h1>
            <p className="text-slate-400 text-sm mb-6 uppercase tracking-wider font-mono">
              Brief assessment report
            </p>

            <div
              className="text-7xl font-bold mb-4 font-display"
              style={{
                background: `linear-gradient(135deg, ${
                  score === 3
                    ? '#00ffa3, #10b981'
                    : score > 0
                    ? '#5994ff, #3b76ff'
                    : '#ef4444, #ff3cac'
                })`,
                WebkitBackgroundClip: 'text',
                WebkitTextFillColor: 'transparent',
              }}
            >
              You got {score}/3 correct
            </div>

            {hasStrike ? (
              <div className="flex items-center gap-2 px-4 py-3 rounded-xl bg-error/10 border border-error/20 text-error text-xs font-semibold justify-center animate-bounce mb-3">
                <Flame size={14} className="fill-error" />
                STRIKE ADDED! Score was 0/3.
              </div>
            ) : (
              <div className="flex items-center gap-2 px-4 py-3 rounded-xl bg-success/10 border border-success/20 text-success text-xs font-semibold justify-center mb-3">
                <CheckCircle2 size={14} />
                Good job! Clear rating achieved.
              </div>
            )}

            <div className="flex justify-center gap-3 mt-4">
              {questions.map((q, idx) => {
                const selected = selectedAnswers[idx];
                const isCorrect = selected === q.correct;
                return (
                  <div
                    key={idx}
                    className={`w-9 h-9 rounded-lg flex items-center justify-center text-xs font-bold border ${
                      isCorrect
                        ? 'bg-success/15 border-success/30 text-success'
                        : 'bg-error/15 border-error/30 text-error'
                    }`}
                  >
                    Q{idx + 1}
                  </div>
                );
              })}
            </div>
          </div>

          <div className="flex items-center gap-2 px-4 py-2 bg-navy-900 border border-white/5 rounded-xl text-[10px] font-mono font-bold text-slate-400 justify-center">
            <div className="w-1.5 h-1.5 rounded-full bg-cyber-purple animate-ping" />
            LOADING NEXT TOPIC IN {countdownTransition} SECONDS...
          </div>
        </div>
      </div>
    );
  }

  const timerColor =
    timeLeft > 60
      ? 'text-cyber-green'
      : timeLeft > 20
      ? 'text-warning animate-pulse'
      : 'text-error animate-pulse font-extrabold';

  return (
    <div className="flex-1 flex flex-col justify-between max-w-3xl mx-auto w-full px-4 py-8 relative">
      <div className="orb orb-blue w-80 h-80 -top-20 -right-20" />

      {/* Header and Timer Bar */}
      <div className="glass-light p-4 rounded-2xl flex flex-col sm:flex-row items-center justify-between gap-3 mb-6 animate-slide-up border border-white/5">
        <div>
          <h1 className="text-lg font-bold text-white font-display">
            Quick Check — 3 Minutes
          </h1>
          <p className="text-slate-400 text-xs mt-0.5">
            Topic Evaluation: <span className="text-accent-300 font-semibold">{topicName}</span>
          </p>
        </div>
        <div className={`flex items-center gap-2 px-4 py-2 bg-navy-950 border border-white/5 rounded-xl text-base font-mono font-bold ${timerColor} shadow-inner`}>
          <Clock size={16} />
          <span>{formatTime(timeLeft)}</span>
        </div>
      </div>

      {error && (
        <div className="mb-4 flex items-start gap-2 rounded-xl border border-warning/20 bg-warning/10 px-4 py-3 text-xs text-warning animate-slide-up">
          <AlertTriangle size={15} className="mt-0.5 shrink-0" />
          <span>
            Live quiz generation failed, so an offline quiz was built from the explanation.
          </span>
        </div>
      )}

      {/* Scrollable Questions list */}
      <div className="space-y-6 animate-slide-up max-h-[60vh] overflow-y-auto pr-1">
        {questions.map((q, qIdx) => {
          const selected = selectedAnswers[qIdx];
          return (
            <div key={q.id} className="glass p-6 sm:p-8">
              <div className="flex items-start gap-3.5 mb-5">
                <span className="w-8 h-8 rounded-lg bg-accent-500/10 border border-accent-500/20 text-accent-400 font-mono font-bold text-xs flex items-center justify-center shrink-0">
                  {q.id.toString().padStart(2, '0')}
                </span>
                <h2 className="text-base sm:text-lg font-semibold text-white leading-relaxed">
                  {q.question}
                </h2>
              </div>

              {/* A-D Options grid */}
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                {q.options.map((opt, optIdx) => {
                  const optChar = String.fromCharCode(65 + optIdx); // A, B, C, D
                  const isSelected = selected === optChar;
                  
                  return (
                    <button
                      key={optChar}
                      type="button"
                      onClick={() => handleSelect(qIdx, optChar)}
                      className={`
                        w-full text-left p-4 rounded-xl flex items-center gap-3
                        transition-all duration-300 border border-transparent cursor-pointer
                        ${
                          isSelected
                            ? 'bg-accent-500/10 border-accent-500 text-white'
                            : 'glass-light hover:border-white/10 hover:bg-white/5 text-slate-300'
                        }
                      `}
                    >
                      <span className={`w-7 h-7 rounded-full flex items-center justify-center text-xs font-bold shrink-0 ${
                        isSelected 
                          ? 'bg-accent-500 text-white' 
                          : 'bg-navy-700 text-slate-400'
                      }`}>
                        {optChar}
                      </span>
                      <span className="text-sm leading-relaxed">{opt}</span>
                    </button>
                  );
                })}
              </div>
            </div>
          );
        })}
      </div>

      {/* Submit Button */}
      <div className="mt-6 animate-slide-up">
        <button
          type="button"
          onClick={handleSubmit}
          className="btn-primary w-full flex items-center justify-center gap-2 py-4 text-base font-bold shadow-lg glow-accent"
        >
          <Trophy size={18} />
          Submit Quiz
          <ArrowRight size={18} />
        </button>
      </div>
    </div>
  );
}
